workflows:
  ios-build:
    name: iOS build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Ensure iOS platform and Podfile setup
        script: |
          if [ ! -f ios/Podfile ]; then
            echo "platform :ios, '15.5'" > ios/Podfile
            cd ios && pod install --repo-update
          fi
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
