workflows:
  ios-build:
    name: iOS Build Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Ensure Podfile exists
        script: |
          if [ ! -f ios/Podfile ]; then
            echo "Creating Podfile..."
            echo "platform :ios, '15.5'" > ios/Podfile
            echo "use_frameworks!" >> ios/Podfile
            echo "use_modular_headers!" >> ios/Podfile
            echo "target 'Runner' do" >> ios/Podfile
            echo "  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))" >> ios/Podfile
            echo "end" >> ios/Podfile
          fi
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
